### ISSUE TITLE
Converter tool

### ISSUE THREAD

**Issue by jacdevos** [robfe/SpecLight#5]
Hi Robfe,

We liked the StoryQ converter (used it in planning meetings to help BA/PO create a staring point for devs).

Robfe uploaded a simple tool to it's at http://codepen.io/robfe/full/MYydBy, but it's not in github yet.

Thanks

**Comment by jacdevos** [comment]
What would be really neat is to build a converter from the Gherkin specification language - maybe use code from SpecFlow to help? 

I like SpecLight since there's so little magic involved (what you see is what you get) and the natural language is not in code (only in report), but it would be nice to leverage the Gherkin spec for conversion since there's so much training and docs for it.

**Comment by robfe** [comment]
speclight only supports a subset of what gherkin's capable of, so I can't aim for 100% compatibility, but I'm happy to make the converter tool more like gherkin if you can be specific about what you need?

**Comment by robfe** [comment]
Ok, it's in source control (c2a073703c880dc6aff6c6fd2eb12076e744ec42) and [hosted on github.io](http://robfe.github.io/SpecLight/converter/) now:

**Comment by jacdevos** [comment]
Excellent! Thanks
