### ISSUE TITLE
Unspecified dependency (System.Web.Webpages) for HTML rendering

### ISSUE THREAD

**Issue by toddb** [robfe/SpecLight#8]
My HTML report is not rendering because the [rendering page](https://github.com/robfe/SpecLight/blob/master/SpecLight/Output/RazorTemplateBase.cs#L6) has a dependency on `System.Web.Webpages`.

Obviously nothing in nuget specifically (https://www.nuget.org/packages?q=System.Web.Webpages). Or where? I see you have it in the csproj as version 1.0.0.0

It appears to be part of the [asp.net mvc set of libraries](http://stackoverflow.com/questions/11246861/could-not-load-file-or-assembly-system-web-webpages). I can't see that you are getting it from RazorGenerator.Templating.

Cheers.

**Comment by robfe** [comment]
Closed by #10
